//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrankenBischof.Docxes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Subjects = new HashSet<Subject>();
        }
    
        public int Id { get; private set; }
        public int SchoolId { get; private set; }
        public string FirstName { get; private set; }
        public string LastName { get; set; }
        public bool IsMale { get; private set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
