//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrankenBischof.Docxes {

    public partial class Document
    {
        public int Id { get; private set; }
        public int SubjectId { get; private set; }
        public string FilePath { get; private set; }
    
        public virtual Subject Subject { get; set; }
    }
}
