//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrankenBischof.Docxes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.Document = new HashSet<Document>();
            this.Note = new HashSet<Note>();
            this.Grade = new HashSet<Grade>();
        }
    
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public System.DateTime Date { get; set; }
        public int Type { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual ICollection<Document> Document { get; set; }
        public virtual ICollection<Note> Note { get; set; }
        public virtual ICollection<Grade> Grade { get; set; }
    }
}
