//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrankenBischof.Docxes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public Nullable<int> EventId { get; set; }
        public int Value { get; set; }
        public int Weight { get; set; }
        public string Comment { get; set; }
    
        public virtual Subject Subject { get; set; }
        public virtual Event Event { get; set; }
    }
}
