//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrankenBischof.Docxes
{
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Events = new HashSet<Event>();
            this.Documents = new HashSet<Document>();
            this.Notes = new HashSet<Note>();
            this.Grades = new HashSet<Grade>();
        }
    
        public int Id { get; private set; }
        public int TeacherId { get; private set; }
        public string Name { get; private set; }
    
        public virtual Teacher Teacher { get; set; }
        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<Note> Notes { get; set; }
        public virtual ICollection<Grade> Grades { get; set; }
    }
}
