//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VrankenBischof.Docxes
{
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public Teacher()
        {
            this.Subjects = new HashSet<Subject>();
        }
    
        public int Id { get; private set; }
        public int SchoolId { get; private set; }
        public string FirstName { get; private set; }
        public string LastName { get; set; }
        public bool IsMale { get; private set; }
    
        public virtual School School { get; set; }
        public virtual ICollection<Subject> Subjects { get; set; }
    }
}
